export const CHANGE_TEXT = "CHANGE_TEXT";
export const ADD_TO_LIST = "ADD_TO_LIST";
export const SET_START_AND_END = "SET_START_AND_END";
export const SET_RECEIVED_DATA = "SET_RECEIVED_DATA";
export const SET_DATA_RETRIEVAL_COMPLETED = "SET_DATA_RETRIEVAL_COMPLETED";
export const RESET_ALL_DATA = "RESET_ALL_DATA";
